### ISSUE TITLE
Como usar no celular?

### ISSUE THREAD

**Issue by Felipe-Souza-Pereira-Lima** [felipecastrosales/Virtual-Store#10]
Vi que é uma aplicação para celular mais não achei o apk para o instalar

**Comment by felipecastrosales** [comment]
Olá Felipe, meu compadre, tudo bem com você? Espero que sim!
Nesse meu último pull request (#9), eu configurei tudo certinho para a geração do apk, para isso, basta você rodar o comando, "flutter build apk". 
Ou, baixe o apk pelo meu [Google Drive](https://drive.google.com/drive/folders/1C3nzcpD-Bc8tln5lfDOVG8Z1pmPHEmeK?usp=sharing).

**Comment by felipecastrosales** [comment]
Felipe, sinta-se a vontade de dar um feedback a respeito da aplicação, irei ficar grato! 😃

**Comment by felipecastrosales** [comment]
Acabei de atualizar o repositório e coloquei uma demo, dá uma olhada, meu compadre!
Espero que tenha gostado ;)

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Olá, Estou bem sim!
OK, irei testar no meu celular e reportarei qualquer erro

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Uma perguntinha?
Como ele realiza as compras?

**Comment by Felipe-Souza-Pereira-Lima** [comment]
As compras são entregues?

**Comment by felipecastrosales** [comment]
Olá @Felipe-Souza-Pereira-Lima, esse aplicativo é apenas uma demonstração. 
Ele não é oficial, e nem há a possibilidade de entrega do mesmo, foi apenas para aprendizado e para compartilhar esse projeto com a comunidade.
Fique a vontade para caso deseje usá-lo de alguma forma.
Você pode realizar as compras criando sua conta, adicionando um produto ao carrinho, e finalizando a compra após isso, mas como supracitado, é apenas uma demonstração.
Caso tenha mais dúvidas ou recomendações, estou a disposição.
Boa noite! Tudo de bom pra você!

**Comment by felipecastrosales** [comment]
Olá @Felipe-Souza-Pereira-Lima, esse aplicativo é apenas uma demonstração.
Ele não é oficial, e nem há a possibilidade de entrega do mesmo, foi apenas para aprendizado e para compartilhar esse projeto com a comunidade.
Fique a vontade para caso deseje usá-lo de alguma forma.
Você pode realizar as compras criando sua conta, adicionando um produto ao carrinho, e finalizando a compra após isso, mas como supracitado, é apenas uma demonstração.
Caso tenha mais dúvidas ou recomendações, estou a disposição.
Boa noite! Tudo de bom pra você!

**Comment by Felipe-Souza-Pereira-Lima** [comment]
Ok, obrigado

**Comment by felipecastrosales** [comment]
Por nada, Felipe!
