### ISSUE TITLE
Firebase setup

### ISSUE THREAD

**Issue by ReidSotkuDev** [felipecastrosales/Virtual-Store#14]
I need assistance or some guidance in how to set up firebase for this application. Do you need to structure the data a certain way or just make a new app and connect.

**Comment by felipecastrosales** [comment]
Hi, @ReidSotkuDev, how are you?
Please, see this issue: https://github.com/felipecastrosales/Virtual-Store/issues/6
Certainly can help you.
Good luck, and if I can help you, I'm available.

**Comment by ReidSotkuDev** [comment]
I can figure it out with the issue, but I would still like to call to
discuss some programming things I think I can help you out and get you some
clients.

**Comment by felipecastrosales** [comment]
That would be really cool, but it's still not my focus.
Please try the procedure.
But your idea is very interesting, let's keep in touch!

Em sáb., 31 de jul. de 2021 às 02:00, ReidSotkuDev ***@***.***>
escreveu:
