### ISSUE TITLE
Cloud firestore firebase settings

### ISSUE THREAD

**Issue by II11II** [felipecastrosales/Virtual-Store#6]
Hi,
Could you provide the fields and tables name or just screen shot of your cloudstore table?

**Comment by felipecastrosales** [comment]
Of course yes! Is a pleasure!!!

(The admins folder has no need for this app, just for the manager)
![image](https://user-images.githubusercontent.com/59374587/98551067-a46f2000-227b-11eb-89b9-8d559b3744e9.png)


Home:
![image](https://user-images.githubusercontent.com/59374587/98548894-d632b780-2278-11eb-9dc2-60e22e7943d7.png)

---

Orders:
![image](https://user-images.githubusercontent.com/59374587/98549084-185bf900-2279-11eb-9806-80bb361c8ce2.png)

---

Places:
![image](https://user-images.githubusercontent.com/59374587/98549122-23168e00-2279-11eb-9a7c-48e5c2790595.png)


---

Products:
![image](https://user-images.githubusercontent.com/59374587/98549152-2b6ec900-2279-11eb-95fb-00a3d85f5b61.png)
![image](https://user-images.githubusercontent.com/59374587/98549183-34f83100-2279-11eb-84e4-31cec12e5c63.png)

---

Users:
![image](https://user-images.githubusercontent.com/59374587/98549227-42152000-2279-11eb-9bf7-de660fa8ae8d.png)


Rename this file below to google-services.json and put it in the folder: Android -> App: 
[json-virtualstore.txt](https://github.com/felipecastrosales/Virtual-Store/files/5510895/json-virtualstore.txt)

---

I hope you can use the app, any questions I am available, have a good day! 😃🚀

**Comment by II11II** [comment]
Thank you )

**Comment by felipecastrosales** [comment]
You´re welcome!
I hope my project can help not only you, but everyone who hires questions!
Any doubt I am available!

**Comment by felipecastrosales** [comment]
You´re welcome!
I hope my project can help not only you, but everyone who hires questions!
Any doubt I am available!
